### ISSUE TITLE
Token Balance Events

### ISSUE THREAD

**Issue by xgmolinax** [StablePay/sdk_l2#24]
When using getAccountTokenBalances() after a Deposit, Transfer or Withdraw operation, the resulting balances are still not updated. Need a way to listen to balance change events.

**Comment by dmolina79** [comment]
This is a duplicate from #16

**Comment by xgmolinax** [comment]
Yes, although that issue does not reference that getAccountTokenBalances() is not working as expected. Should check out if its working properly as for now, I could not validate if pending transactions are returned correctly.
