### ISSUE TITLE
I want to send 100% of my ETH balance

### ISSUE THREAD

**Issue by eriksuazo95** [StablePay/sdk_l2#46]
A transaction error was encountered when wanting to send 100% of the ETH balance in L2 to another wallet

https://zkscan.io/explorer/transactions/3ac74ae6b5321b9ab2071cbcfdb508c139e01d0d45294d35196f11db443453b4

**Comment by dougstorm** [comment]
This should go here
https://github.com/StablePay/stablepay-app/issues
